feat: add git-continue
tj/git-extras pull request #1176
Opened 2024-11-04 19:04 UTC by oikarinen

Also refactor `git-abort` to parse action from the called file name.

There's a promise for this in #865 but that was a long time ago.

2024-11-12 22:01 UTC, hyperupcall requested changes
Thanks! Looks good, I have a few suggestions

2024-11-12 22:01 UTC, hyperupcall commented on bin/git-abort
> +function discover_action() {
I'm not a huge fan of this function, but I'm good with this for now.

2024-11-18 17:10 UTC, oikarinen commented on bin/git-abort
> +set -xuo pipefail
Hey thanks for the catch, looks like copilot had a clitch that i didn't notice 🥹

2024-11-22 19:12 UTC, oikarinen commented on tests/helper.py
> -from testpath import MockCommand, modified_env
These were not used, sorry for whitespace change for the file that `ruff` caused.

2024-11-27 05:53 UTC, hyperupcall commented
Thanks for the changes, LGTM. @spacewander what do you think?

2024-11-27 05:53 UTC, hyperupcall approved these changes

2024-11-28 08:50 UTC, merged

2024-11-28 08:50 UTC, spacewander commented
Merged. Thanks!