Allow use of GITHUB_TOKEN env var
tj/git-extras pull request #1177
Opened 2024-11-13 20:52 UTC by nim65s

Hi,

`git-fork` & `git-pull-request` currently require to set github token in git config global file.
I would like to keep this file versionned and public on github, so I would prefer not having to put secrets inside.

A common solution to this issue is to pass that token through the `GITHUB_TOKEN` environment variable instead.

Here is a simple commit implementing and documenting that.

ref. #839

2024-11-14 03:28 UTC, spacewander commented on bin/git-fork
> +  github_personal_access_token=$GITHUB_TOKEN
Need to quote $GITHUB_TOKEN to make shellcheck happy

2024-11-14 03:28 UTC, spacewander commented on bin/git-fork
> +if test -z "${GITHUB_TOKEN}"; then
Better to use `test -n`, and put the highest priority branch (using GITHUB_TOKEN) as the first one. This way is more readable.

2024-11-14 03:28 UTC, spacewander commented on man/git-fork.md
Why git-fork.1 is not updated?

2024-11-14 10:16 UTC, nim65s commented
Thanks for the review !
I've added the requested changes

2024-11-14 17:36 UTC, hyperupcall requested changes
I support this `GITHUB_TOKEN` feature! I just had a few notes

2024-11-14 17:36 UTC, hyperupcall commented on bin/git-fork
> +  github_personal_access_token=$(git config git-extras.github-personal-access-token)
```suggestion
  github_personal_access_token=$(git config --default '' git-extras.github-personal-access-token)
```

Would recommend passing `--default` to make code more robust. (in the future, `errexit` may be enabled, and this invocation shouldn't exit the entire script if the config key could not be found).

2024-11-14 17:58 UTC, nim65s commented
@hyperupcall what would you think about dropping that switch, and using only one
```
github_personal_access_token=$(git config --default "${GITHUB_TOKEN}" git-extras.github-personal-access-token)
```
?

2024-11-14 18:10 UTC, hyperupcall commented
@nim65s That's perfect!

2024-11-14 19:26 UTC, hyperupcall approved these changes

2024-11-15 02:49 UTC, spacewander commented on man/git-pull-request.md
> -Use `git config --global --add git-extras.github-personal-access-token <your-personal-access-token>`
Could you also regenerate the git-pull-request.1 file?

2024-11-16 18:32 UTC, hyperupcall commented
Great, thanks!

2024-11-16 18:33 UTC, merged